apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2  # Nombre de répliques du microservice
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: silou19/pfe-e-com-product-service:latest # Remplace <username> par ton nom d'utilisateur Docker Hub
          ports:
            - containerPort: 8002  # Le port sur lequel ton microservice écoute
          env:
            - name: NODE_ENV
              value: "production"  # L'environnement de production

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30082  # Choose a port between 30000-32767
